1. Create two arrays of random integers between 10 and 20. 
The shape of the array must be (2, 3) for the first array 
and (1, 3) for the second array. Check the shape of the 
arrays. Ensure that the results are reproducible. 

In [14]:
import numpy as np

# Creating random array
rng = np.random.default_rng(seed=42)
arr1 = rng.integers(low=10, high=20, size=(2,3))
print(arr1)


np.shape(arr1)


[[10 17 16]
 [14 14 18]]


(2, 3)

In [13]:
arr2 = rng.integers(low=10, high=20, size=(1, 3))
print(arr2)

np.shape(arr2)



[[17 15 11]]


(1, 3)

2. Write a code to add the two arrays you just created in 
question 1. Check the shape of the resulting array. Explain 
why the resulting shape is that of the bigger array from the 
two arrays created in question 1. 

In [15]:
# addition of 2 arrays

arr_add = np.add(arr1, arr2)
print(arr_add)

np.shape(arr_add)

[[27 32 27]
 [31 29 29]]


(2, 3)

In [ ]:
This is because arrays of different dimension cannot add up, so it first 