1. Create a one-dimensional array with random integers 
between 0 and 20. The size of the array is 10. Ensure that 
the results are reproducible. 

In [7]:
import numpy as np

rng = np.random.default_rng(seed=42)
arr = rng.integers(low=0, high=20, size=10)
arr


array([ 1, 15, 13,  8,  8, 17,  1, 13,  4,  1])

2. Using slicing, create a subset array of 3 integers from the 
array you created in question 1. The first integer is at index 
2, the second integer is at index 4, and the third index is 
at index 7. 

In [16]:
arr2 = arr[[2, 4, 7]]
arr2

array([13,  8, 13])

3. Create a two-dimensional array from the list below. Check the 
dimensions and shape of your array.

In [23]:
My_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], 
           [11, 12, 13, 14, 15]]


In [24]:
arr3 = np.array(My_list)
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [26]:
arr3.ndim

2

In [32]:
arr4 = arr3[0, 2], arr3[1, 2], arr3[2, 2]
arr4

(np.int64(3), np.int64(8), np.int64(13))

4. Create a three-dimensional array from the nested list below: 


In [38]:
list1 = [[[1, 2, 3, 4, 5], 
           [6, 7, 8, 9, 10], 
           [11, 12, 13, 14, 15]]]


Using slicing, write code that creates a sublist from the 
array you created. Your code should return an array of 
numbers (4, 8, and 15). 

In [39]:
arr5 = np.array(list1)
arr5

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [40]:
arr5.ndim

3

In [42]:
sub_list = arr5[0,0,3], arr5[0,1,2], arr5[0,2,4]
sub_list

(np.int64(4), np.int64(8), np.int64(15))