## Day 2: Creating and Manipulating Arrays   

Master NumPy arrays by practicing creation, shape/size checks, and basic manipulation for data analysis.

1. Write code to import NumPy into your script. Check the 
version of NumPy installed. 

In [5]:
import numpy as np
(np.__version__)


'2.4.0'

2. Here is a list below:    
list1 = [2, 3, 4, 6]    
Create a one-dimensional array from the list above. Write 
another line of code to check the shape and size of your 
array. 
Write a function (Python function) that takes this array and 
returns a new array with all the values in the original array 
reversed. 

In [20]:
# Creating one dimentional array
list1 = [2, 3, 4, 6]
arr = np.array(list1)
arr


array([2, 3, 4, 6])

In [22]:
# Checking shape of array
arr.shape

(4,)

In [24]:
# Checking size of array
arr.size

4

arr.shape → structure (rows × columns).

arr.size → total count of elements.

Python Function to reverse array

In [36]:
# Using function to reverse array
def reverse_array (array):
    return array[::-1]

# Creating an array 
arr = np.array(list1)

# Reversing array using function
arr_reversed = reverse_array(arr)
arr_reversed

array([6, 4, 3, 2])

Using np.flip() function to reverse array

In [43]:
arr_flipped = np.flip(arr)
arr_flipped

array([6, 4, 3, 2])

3. list1 = [2, 3, 4, 6]    
list2 = [8, 10, 12, 14]    
Create an array from the two lists above. Then write code to 
check the shape, dimensions,  and data type of the array. 

In [50]:
# Creating an array from the two list
list1 = [2, 3, 4, 6] 
list2 = [8, 10, 12, 14] 

arr = np.array([list1,list2])
arr

array([[ 2,  3,  4,  6],
       [ 8, 10, 12, 14]])

In [63]:
# to details of the array
arr_shape = arr.shape
arr_dimension = arr.ndim
arr_type = arr.dtype
arr_details = [arr_shape, arr_dimension, arr_type]
arr_details

[(2, 4), 2, dtype('int64')]

Note : NumPy defaults to int32 on 32‑bit systems and int64 on 64‑bit systems, so the dtype depends on your machine’s architecture.

4. list1 = [2, 3, 4, 6]    
list2 = [8, 10.1, 12, 14]    
list3 = [16, 18, 20, 22.1]    
Create an array from the three (3) lists above. Take note 
that some of the lists contain floats. Create an array that 
will have an int64 data type.

In [74]:
list1 = [2, 3, 4, 6] 
list2 = [8, 10.1, 12, 14]
list3 = [16, 18, 20, 22.1] 

# Creating an array from the lists
arr = np.array([list1, list2, list3])
arr

array([[ 2. ,  3. ,  4. ,  6. ],
       [ 8. , 10.1, 12. , 14. ],
       [16. , 18. , 20. , 22.1]])

In [75]:
# Convertin the array to int64 data type
int64_arr = arr.astype(np.int64)
int64_arr

array([[ 2,  3,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [77]:
# print array data type
int64_arr.dtype

dtype('int64')

We can as well specify the data type when the arry is created.

In [79]:
list1 = [2, 3, 4, 6] 
list2 = [8, 10.1, 12, 14]
list3 = [16, 18, 20, 22.1] 

# Creating an array from the lists
arr = np.array([list1, list2, list3], dtype='int64')
arr

array([[ 2,  3,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

5. NumPy arrays are homogeneous, so mixed integers and floats become a single type—by default float64.

In [81]:
# list of integers and floats
lst = [1, 2.5, 3, 4, 2, 5]

# Creating an array from a list of floats and integers 
my_array = np.array(lst)
my_array.dtype

dtype('float64')