# Day 12: Array Sorting and Filtering 



1. Create an array using the list below. Write code to sort the 
array in ascending order: first sort by columns, then by 
rows. Create a new variable for each of the sorted arrays.

In [3]:
list1 = [[12, 34, 56], [12, 13, 8,], [6, 5, 10]] 


In [7]:
import numpy as np

arr = np.array(list1)

# sort the array in ascending order by columns
sorted_arr = np.sort(arr, axis=0)
sorted_arr

array([[ 6,  5,  8],
       [12, 13, 10],
       [12, 34, 56]])

2. Using NumPy slicing, write a code that slices these 
numbers in this order [8, 12, 56] from the array sorted by 
columns (question 1). Create a new variable.  

In [14]:
sliced_arr = np.array([
    sorted_arr[0, 2],   # 8
    sorted_arr[1, 0],   # 12
    sorted_arr[2, 2]    # 56
])
sliced_arr


array([ 8, 12, 56])

3. Create a 2-dimensional array of random integers between 
100 and -100 in the shape (3, 3). Use the np.where() 
function to replace all negative values in the array with 0. 
Use a seed to save the random numbers generated. 

In [20]:
rng = np.random.default_rng(seed=42)

arr2 = rng.integers(-100, 100, size=(3,3))
arr2 = np.where(arr2 < 0, 0, arr2)
arr2

array([[ 0, 54, 30],
       [ 0,  0, 71],
       [ 0, 39,  0]])

4. Here is a list below:   

list1 = [[12, 23, 34, 34], [13, 13, 20, 21]]    

Create an array from the list above.    
Using the np.unique() function, return the unique 
elements in the array and the counts of each unique 
element (how many times each element appears in 
the list). 

In [31]:
list1 = [[12, 23, 34, 34], [13, 13, 20, 21]]    

arr3 = np.array(list1)
unique_elements, counts = np.unique(arr3, return_counts=True)
print(f"The unique elements are: {unique_elements}, and their respective count {counts}")

The unique elements are: [12 13 20 21 23 34], and their respective count [1 2 1 1 1 2]


5. Use the np.flatten() function to flatten the nested array 
you created in question 4. 

In [30]:
flatten_arr = arr3.flatten()
flatten_arr

array([12, 23, 34, 34, 13, 13, 20, 21])